# Generated by Django 3.2.9 on 2021-11-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='country',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
