# Generated by Django 3.2.9 on 2021-11-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imanager', '0003_alter_category_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
