# Generated by Django 3.2.9 on 2021-11-05 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imanager', '0007_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(blank=True, max_length=250)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imanager.category')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
