# Generated by Django 3.2.9 on 2021-11-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imanager', '0008_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='items',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='unit_price',
            field=models.FloatField(null=True),
        ),
    ]
