# Generated by Django 3.2.9 on 2021-11-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imanager', '0009_auto_20211106_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(max_length=250),
        ),
    ]
