# Generated by Django 3.2.9 on 2021-11-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imanager', '0010_alter_items_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator', models.CharField(blank=True, max_length=50)),
                ('item_name', models.CharField(max_length=50)),
                ('quantity_requested', models.IntegerField(verbose_name='Quantity Requested')),
                ('stage', models.CharField(blank=True, max_length=30, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'itemrequest',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='initiator',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='items',
            name='initiator',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
