# Generated by Django 3.2.9 on 2021-11-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imanager', '0011_auto_20211106_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemrequest',
            old_name='initiator',
            new_name='country',
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='requester',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='quantity_requested',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='stage',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
