# Generated by Django 3.2.9 on 2021-11-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imanager', '0012_auto_20211106_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='quantity_requested',
            field=models.IntegerField(null=True),
        ),
    ]
