# Generated by Django 3.2.9 on 2021-11-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imanager', '0014_itemrequest_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='item_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='stage',
            field=models.CharField(blank=True, default='pending', max_length=30),
        ),
    ]
