# Generated by Django 3.2.9 on 2021-11-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imanager', '0017_auto_20211107_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='item_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
