# Generated by Django 3.2.9 on 2021-11-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imanager', '0018_alter_itemrequest_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='category',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='item_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
