# Generated by Django 3.2.9 on 2021-11-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imanager', '0019_auto_20211107_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='head_decision',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='manager_decision',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='quantity_given',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
