# Generated by Django 3.2.9 on 2021-11-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imanager', '0021_itemrequest_temporary_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='pending_approval',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
