# Generated by Django 3.2.9 on 2021-11-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imanager', '0022_items_pending_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=254)),
                ('inventManager', models.CharField(blank=True, max_length=250)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'managerapproval',
            },
        ),
    ]
