# Generated by Django 3.2.9 on 2021-11-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imanager', '0023_managerapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerapproval',
            name='country',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
