# Generated by Django 3.2.9 on 2021-11-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imanager', '0024_managerapproval_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='quantity_remain',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
