# Generated by Django 3.2.9 on 2021-11-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imanager', '0025_items_quantity_remain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrequest',
            name='temporary_given',
        ),
        migrations.RemoveField(
            model_name='items',
            name='quantity_remain',
        ),
    ]
